version: '3.7'

services:

  webapp:
    container_name: bmpapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
